### ISSUE TITLE
Team Discussion on CI 

### ISSUE THREAD

**Issue by JoshSevy** [the-turing-index/web-app#17]
### Feature Categories:
- Discuss getting continuous integrations setup for the project per rubric
- What works easiest and best for whole team?

**Describe the feature/Bug your gonna work on**
Per Rubric:
CI & Deployment

4: App has CI and successfully builds by day 5 and is deployed successfully after every PR merges. Logs should show that failed builds are very quickly addressed.
3: App has CI and successfully builds halfway through the project, and on due day.
2: App has CI and successfully build on the due day.
1: App does not have CI setup but does successfully deploy.

**Additional context**
Add any other context or screenshots about the feature.

**Comment by ajtran303** [comment]
Cool, thanks for bringing this up.

There are two repos, so we will need ci/cd for the front and back.

**Comment by ajtran303** [comment]
> by day 5

Since the project started on Tuesday, that means to meet this requirement, we need to build CI by Sunday and set up Deployment too

**Comment by ajtran303** [comment]
The API has CI/CD set up - upon merging the first PR, it should auto-deploy to https://obscure-stream-58473.herokuapp.com/
