### ISSUE TITLE
Discuss potentially Backup Plan if SVG method is to problematic

### ISSUE THREAD

**Issue by JoshSevy** [the-turing-index/web-app#40]
### Feature Categories:

- [ ] Angular
- [ ] SCSS / Styling
- [ ] Testing
- [ ] UI 
- [ ] BugFix
- [ ] Planning/Game Plan

**Describe the feature/Bug your gonna work on**
Create a backup plan just in case there is an issues with incorporating angular into a svg file. 
A fail safe meeting of sorts. 

**Additional context**
Add any other context or screenshots about the feature.

**Comment by ajtran303** [comment]
![Screen Shot 2020-10-29 at 2 15 44 PM](https://user-images.githubusercontent.com/31839316/97627625-3f046f00-19f1-11eb-9a35-219ea078453e.png)
Throwing in an idea
